source ~/.dotfiles/zsh/env.zsh
source ~/.dotfiles/zsh/path.zsh
source ~/.dotfiles/zsh/others.zsh
source ~/.dotfiles/zsh/hooks.zsh
source ~/.dotfiles/zsh/options.zsh
source ~/.dotfiles/zsh/functions/functions.zsh
source ~/.dotfiles/zsh/functions/git-functions.zsh
source ~/.dotfiles/zsh/bindings.zsh
source ~/.dotfiles/zsh/locale.zsh
source ~/.dotfiles/zsh/alias.zsh
